version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.11.23-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
